### ISSUE TITLE
Make sure multivalued elements in the model are parsed correctly

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#124]
This needs some treatment on both the parsing and converting side.

Basically, it goes like this:
1. All `multivalued` fields in the sssom spec (https://github.com/mapping-commons/sssom-py/blob/master/schema/sssom.yaml) can be represented as `|`-separated values in a table cell. (this should be in the dataclasses, _not_ determined by parsing the spec!)
2. When they are parsed into the metamodel (to_mapping_set_document, parsers.py), we need to ensure that they are parsed as multi-valued.

**Comment by matentzn** [comment]
My guess: 

| ... | creator_id |
| -- | -- |
| .. | orcid:001\|orcid:002 |

When parsing the value, we neet to do something like value.spit("|") and pass a list (ideally whitespace `strip`-ped) to the linkml object.

**Comment by hrshdhgd** [comment]
Fixed by #163
