### ISSUE TITLE
sdist + setup.cfg does not include jsonld context files

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#136]

**Comment by cthoyt** [comment]
switching to a src/ layout and using my boilerplate setup.cfg information might fix this. Have you been able to come up with a unit test that reflects this issue?

**Comment by matentzn** [comment]
To be honest, no - but you don't really need to -> if you run the packaging system, you can just look insider whether all required files are present.. Not sure whether its worth to have a unit tests that runs the packaging system, and then checks whether all required files have been correctly packed - it would require us to maintain yet another list of resources. I would prefer moving sssom-py to a standard layout at some point when we have a bit more time and convince ourselves that anything we stick into the src/resources folder end up in the distro.

**Comment by matentzn** [comment]
Does not need to be done anymore, or files that have to are now packaged
