### ISSUE TITLE
sssom.yaml not found 

### ISSUE THREAD

**Issue by hrshdhgd** [mapping-commons/sssom-py#183]
When released to pypi and installed locally:

on running: `sssom convert test/tests/data/basic.tsv --output-format rdf`

I get the following error:

`FileNotFoundError: [Errno 2] No such file or directory: '/.../envs/test-sssom/lib/python3.9/site-packages/sssom/sssom.yaml'`

**Comment by hrshdhgd** [comment]
When the tar file is downloaded separately, `sssom.yaml` does exist in the package folder

**Comment by matentzn** [comment]
This issue makes me go ballistic man, and I am so Zen, I could autmeditate the Dalai Lama..

**Comment by hrshdhgd** [comment]
I think I know the reason ... just need to prove it. `tox` has something to do with it.

**Comment by hrshdhgd** [comment]
I think [this may be responsible](https://github.com/mapping-commons/sssom-py/blob/a2eb47254bc66d86e0ac5c05bdb8f5f54f78ed94/setup.cfg#L131) to support my comment above.

**Comment by cthoyt** [comment]
> I think [this may be responsible](https://github.com/mapping-commons/sssom-py/blob/a2eb47254bc66d86e0ac5c05bdb8f5f54f78ed94/setup.cfg#L131) to support my comment above.
> 
> ```
> [coverage:paths]
> source =
>     sssom
>     .tox/*/lib/python*/site-packages/sssom
> ```

Nope, tox doesn't have anything to do with this. Check the way that the packaging is being done, specifically this https://github.com/mapping-commons/sssom-py/blob/a2eb47254bc66d86e0ac5c05bdb8f5f54f78ed94/setup.cfg#L85-L88

**Comment by cthoyt** [comment]
This would be an excellent time to switch to src/ layout and the appropriate configuration for that which fixes a lot of these issues without any extra thought added

**Comment by hrshdhgd** [comment]
Figured it out! [This](https://python-packaging.readthedocs.io/en/latest/non-code-files.html) was the missing link!

"In order for these files to be copied at install time to the package’s folder inside site-packages, you’ll need to supply include_package_data=True to the setup() function."

**Comment by hrshdhgd** [comment]
#185 fixes this issue. I have released this to pypi and tested it. It works!

**Comment by matentzn** [comment]
Awesome!
