### ISSUE TITLE
Unpin linkml-runtime version

### ISSUE THREAD

**Issue by hrshdhgd** [mapping-commons/sssom-py#188]
The new release of `linkml-runtime` which is in turn dependent on `rdflib_shim` was causing errors in tests. [Issue created here](https://github.com/linkml/linkml/issues/529#issue-1085308851). Eventually we would like to use the latest versions as newer stable versions are released. The P.R. reflecting the pinned version is [here](https://github.com/mapping-commons/sssom-py/pull/163#issuecomment-998673725).

**Comment by cmungall** [comment]
I think this is a fantom issue?

This PR works:

 *  #190
