### ISSUE TITLE
Tidy up README.md

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/sssom-py#189]
Why are there links to old and new docs?

Just get rid of the old docs and have a link to the canonical. If there is content that is in old and not new, prioritize moving across

I note the new docs don't have basic stuff like installation

**Comment by hrshdhgd** [comment]
The new docs do have[ installation instructions](https://mapping-commons.github.io/sssom-py/installation.html). I will get rid of the old documentation since it is obsolete and everything in included in the new one.
