### ISSUE TITLE
current sssom-py requires curie_map to be present

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#2]
I think this makes sense, but we should make it explicit in the spec.

**Comment by matentzn** [comment]
Also, along the same lines, we need to probably allow to refer to external curie_maps and decide on, from OWL -> TSV, whether we want to allow something like OBO assumption or not.

**Comment by cmungall** [comment]
yeh, I'm trying to run `sssom cliquesummary` over mh_mapping_initiative files just now but it's failing...

it seems a bit strict as some operations like cliquesummary require no expansion to rdf - perhaps the raising of an error could be delayed to when any rdf expansion takes place (and allow passing in of a separate yml)

**Comment by matentzn** [comment]
I agree; imo it would be ok to actually try the sssom default curie map first and only if that fails throw an error - the downside is that the RDF serialisation may unfold to the wrong URI namespaces.. I am happy for the curie map to be optional, but from the client perspective (that's what we do in dosdp tools as well) it would probably be better to make a parameter like `--use-defaut-curie-map` to make the user at least make that choice consciously..

**Comment by cmungall** [comment]
actually it's not an imposition to ask for a yml file, I added an opt to do this, e.g

`sssom cliquesummary -i ../mh_mapping_initiative/mappings/hp_doid_pistoia_sssom.tsv -m  ../mh_mapping_initiative/mappings/hp_doid_pistoia_sssom.yml -o summary.tsv`

**Comment by matentzn** [comment]
As discussed, lets be super strict for now and require it. That precludes bad practice. I would rather have a second method that generates some default metadata.
