### ISSUE TITLE
sssom-py is much too slow

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#202]
We need to figure out why that is first of all, i.e. which functions are so inefficient, and then working on improving efficiency. First goal:

- [ ] A small document of 100 mappings should be processable in 1 second.

**Comment by matentzn** [comment]
Thank you @hrshdhgd this is a great analysis! You can put it a bit on the backburner now and we get back to it later!

**Comment by joeflack4** [comment]
Agree it is too slow, and also a good analysis!

**Comment by matentzn** [comment]
Writing write_owl(msdf1,f) for large msdfs takes a huge amount of time (100MB tsv ~ > 2 hours)

**Comment by matentzn** [comment]
```
(sssom) ➜  ontology git:(master) ✗ wc -l ../mappings/oba-all-phenotype.sssom.tsv
 1712464 ../mappings/oba-all-phenotype.sssom.tsv
(sssom) ➜  ontology git:(master) ✗ sssom filter ../mappings/oba-all-phenotype.sssom.tsv -o ../mappings/oba-all-hp-phenotype.sssom.tsv --subject_id HP:% --object_id OBA:%
```

This should be basically instant but takes 30 minutes. Maybe bypass linkml for certain operations?

**Comment by hrshdhgd** [comment]
Closing this for now in favor of https://github.com/mapping-commons/sssom-py/pull/462 . Feel free to re-open a new issue with exact location of latency improvement needed.
