### ISSUE TITLE
New command: validate

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#21]
Simple variation of the parser that returns true or false and warnings.

**Comment by cthoyt** [comment]
Was just thinking about how this would be nice. Want me to start a simple PR?

**Comment by matentzn** [comment]
Have at it! I could really use your help also with the architecture of this code base.. If you have any suggestions, let me know. Its very hacky at the moment.

**Comment by hrshdhgd** [comment]
Waiting to confirm if the above commit satisfies this ticket before closing it.

**Comment by cmungall** [comment]
@hrshdhgd - are these commits part of a PR?

**Comment by hrshdhgd** [comment]
yes. `cli_edit`. Still working on it.

**Comment by cmungall** [comment]
always make a PR - you can mark it as draft if not ready

**Comment by hrshdhgd** [comment]
I meant #50 is the draft

**Comment by matentzn** [comment]
I think for the validate command, it would be good if:

1. It would check @cthoyt and my 5 star  proposal https://github.com/mapping-commons/SSSOM/pull/69 and implement 3 and 4 star computationally
2. Make sure that all fields that can take multiple values are implemented correctly (#124)

**Comment by matentzn** [comment]
Doing this well is now getting to the top of the list.

**Comment by matentzn** [comment]
Prerequisite for this issue here is https://github.com/mapping-commons/sssom-py/issues/124

**Comment by hrshdhgd** [comment]
Fixed by #270
