### ISSUE TITLE
Clarify source of truth for sssom.yaml

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/sssom-py#220]
discussing this with @hrshdhgd 

This exists in sssom-py and here:

https://github.com/mapping-commons/sssom/blob/master/model/schema/sssom.yaml

I assume the main sssom repo is the SOT and there is a manual inter-repo cp

there is a danger someone forgets this and edits the sssom-py version in place

Short term fix: Add a Makefile target here that will do a curl to sync this or similar, and add a `#` comment at the top saying not to edit

Longer term: consider renaming this repo sssom-utils and distributing the object model in sssom (probably overkill but this is how we do it elsewhere)

**Comment by matentzn** [comment]
Yes, the makefile that we used for building the data model classes etc downloads the schema first:
https://github.com/mapping-commons/sssom-py/blob/master/Makefile#L3

I don't think that danger is that high, as they need to pass through review :)

**Comment by matentzn** [comment]
This is now clarified. sssom_schema.yaml in the sssom repo is the source of truth, it was deleted here.
