### ISSUE TITLE
Make sure that `parse` can work without needing to pass a metadata `.yml`

### ISSUE THREAD

**Issue by joeflack4** [mapping-commons/sssom-py#228]
See: https://github.com/mapping-commons/sssom-py/issues/227#issuecomment-1101205374

The following should work w/out needing a metadata `.yml`:
`sssom parse omim.json -I obographs-json -o omim.sssom.tsv`

It should warn and populate with defaults if any of the following are missing:
- license
- (the other ones in the yaml)

And should have the prefixes for HGNC, Orphanet, etc loaded.

**Comment by matentzn** [comment]
@joeflack4 We are working on related code so its probably best if @hrshdhgd takes care of this.

**Comment by cmungall** [comment]
Note that it's now possible to use OAK to export SSSOM on either a per-term or per-ontology basis

https://incatools.github.io/ontology-access-kit/cli.html#runoak-mappings

longer term we may want sssom-py to focus on processing operations and leave conversion operations to other libs?

**Comment by matentzn** [comment]
I think there are so many non-ontology parsing processes we are working on (alignment API, complex map), that probably some redundancy is unavoidable. Basically the only piece of overlap is  the obographs json parser - I think this is ok.

**Comment by cmungall** [comment]
Agreed, just wanted to make sure we weren’t spending too much time on it

**Comment by matentzn** [comment]
Hopefully fixed by #238
