### ISSUE TITLE
ICD10WHO does not work in `sssom parse`

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#260]
Reproducible example:

```
wget "https://www.dropbox.com/s/8sx79nki2h4pmuk/mirror-mondo.json?dl=0" -O mirror-mondo.json
wget "https://raw.githubusercontent.com/monarch-initiative/mondo/master/src/ontology/metadata/mondo.sssom.config.yml" -O mondo.sssom.config.yml
sssom parse mirror-mondo.json -I obographs-json -m mondo.sssom.config.yml -o test.sssom.tsv
grep -o 'ICD10WHO' mirror-mondo.json | wc -l
grep -o 'ICD10CM' mirror-mondo.json | wc -l
grep -o 'ICD10WHO' test.sssom.tsv | wc -l
grep -o 'ICD10CM' test.sssom.tsv | wc -l
```

Output:

```
grep -o 'ICD10WHO' mirror-mondo.json | wc -l
      18
grep -o 'ICD10CM' mirror-mondo.json | wc -l
    8351
grep -o 'ICD10WHO' test.sssom.tsv | wc -l
    7412
grep -o 'ICD10CM' test.sssom.tsv | wc -l
    8346
```

Clearly sssom py made up about 7400 mappings between mondo and icd10who..

**Comment by hrshdhgd** [comment]
I am looking into this now. So for `xref_id = 'http://apps.who.int/classifications/icd10/browse/2010/en#/Q04.3 `, `curie_from_uri(xref_id, prefix_map)` returns `ICD10WHO:Q04.3`. Is this correct? If so, then this is one of the many examples where `ICD10WHO:XXXX` are getting mapped. Hence the numbers don't seem to add up.

**Comment by matentzn** [comment]
Wait http://apps.who.int/classifications/icd10/browse/2010/en#/Q04.3 exists in verbatim in the source mondo.json?

**Comment by hrshdhgd** [comment]
Yes

**Comment by matentzn** [comment]
Not a sssom py issue.
