### ISSUE TITLE
Discuss: Add functionality to check if a mapping is to or from an obsolete

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/sssom-py#27]
This would be v useful, but is it scope creep? does this belong instead in robot? cc @balhoff

**Comment by matentzn** [comment]
This is definitely scope Creep - in some way it already is in robot (use in logical axioms), but perhaps there is something more systematic to be done, like include-listing all properties allowed to be on obsolete classes. For known reasons this won't easily work with hasDbXref

**Comment by matentzn** [comment]
Closing this for now as I dont think this should be addressed here as part of sssom-py
