### ISSUE TITLE
Validate() should be run as part of write_table()

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#271]
It will cause a lot of errors at first, but overall, it will lead to better mapping data. The suggestion is that whenever we call `write_table()`, the final part of all sssom generating CLI methods, we should run the validator to make sure we only ever output legal sssom.

**Comment by cmungall** [comment]
I suggest parameterizing and allowing overrides, it may be necessary to occasionally write something incorrect in order to repair it.
