### ISSUE TITLE
Customizing mapping of ontologies to SSSOM, including making nodes for literals

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/sssom-py#28]
When making an sssom from an ontology there are multiple points of configuration

 - what predicate to use for a bare xref (where xrefs are used)
 - what confidence value to use. See https://github.com/cmungall/obo-scripts/blob/master/obo-xrefs-to-sssom.pl

Rather than a complex configuration, I think it makes sense to have a standard ontology representation and a deterministic mapping. We would then do either pre-processing on the ontology (e.g. robot/sparql) or on the sssom file.

Another thing that would be very useful for mapping is to translate literals into nodes, potentially performing stemming etc. Then lexical matching becomes transitive closure over, e.g. T1 -> label -> T2. This has advantages for boomer as we get a combined lexical/synonym analysis, cc @balhoff -- however, this could be considered scope creep for sssom-py

**Comment by matentzn** [comment]
@cmungall can you clarify the action items here? I also do not understand this sentence:

> Rather than a complex configuration, I think it makes sense to have a standard ontology representation and a deterministic mapping. We would then do either pre-processing on the ontology (e.g. robot/sparql) or on the sssom file.

**Comment by cmungall** [comment]
I just mean keep it simple. Map xref to xref. People can either do pre-processing on the ontology using robot (e.g. custom convert xrefs to different skos predicates) or in sssom-py (e.g via the powerful dosql command)

**Comment by matentzn** [comment]
Ok, I agree. I would not do any predicate remapping in SSSOM (say xref to related match), but we can consider a new method `sssom map-predicates` or some such that takes in a predicate map and allows changing the predicate from one thing to something else. The advantage would be that this way, we could also deal with the annoying `skos:exactMatch` vs `owl:equivalentClass` problem - I still don't know when to use the one and when to use the other when talking about owl:Class subject/objects.

**Comment by matentzn** [comment]
Closing this for now, as we can do most in dosql, and nodes as literals needs a better more detailed ticket

**Comment by matentzn** [comment]
-
