### ISSUE TITLE
New method sssom annotate

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#280]
To integrate SSSOM more into automated pipelines, it would be super cool to be able to annotate a mapping sets from the command line, especially to support dynamic versioning.

```
sssom annotate --mapping_set_id http://w3id.org/my/mapping.sssom.tsv --mapping_set_version 2021-01-01
```

The idea would be to add a dynamic decorator to click that generates long option (no short ones) from the SSSOM spec dynamically, and then allows setting their values. See something like https://stackoverflow.com/questions/50499340/specify-options-and-arguments-dynamically.

We only care about MappingSet metadata, not mapping metadata!

**Comment by hrshdhgd** [comment]
@matentzn , now in the above example, if `mapping_set_id` already exists in the metadata, does the above command replace with the new value or keep the original one?

**Comment by matentzn** [comment]
> @matentzn , now in the above example, if mapping_set_id already exists in the metadata, does the above command replace with the new value or keep the original one? As of now I've implemented replacement of value.

I think this is the right behaviour! Generally, replacement.
