### ISSUE TITLE
Code accepted with failing build

### ISSUE THREAD

**Issue by cthoyt** [mapping-commons/sssom-py#294]
@hrshdhgd @matentzn 

it's really bad development practice to start letting tests fail. aren't there some branch protection rules to make sure under no circumstances is code allowed to be put in main branch that's failing tests?

**Comment by matentzn** [comment]
We never accept code with failing builds.. ever.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/7070631/182362936-d41e4478-a3f7-4558-a0a9-40839e3af438.png">

**Comment by matentzn** [comment]
The problem here is the flake 8 dependency thing I think.

**Comment by cthoyt** [comment]
I just saw the following on the homepage and was very confused

<img width="1341" alt="Screen Shot 2022-08-02 at 13 25 29" src="https://user-images.githubusercontent.com/5069736/182363588-42217c76-8fc6-419c-b8b6-34f9f86e6ecc.png">
 
This isn't the first time we've been burned by flake8 updates. I guess we should start annotating a maximum version for this dependency in our repos' linting configuations

**Comment by hrshdhgd** [comment]
Fixed!
