### ISSUE TITLE
parse embedded mode: flag true and default true makes no sense

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#304]
```
"-E",
    "--embedded-mode",
    default=True,
    is_flag=True,
```

How could it theoretically be switched off?

**Comment by hrshdhgd** [comment]
[`is_flag` and `default`](https://click.palletsprojects.com/en/8.1.x/options/#boolean-flags) are `click` options. So the part missing is `"--embedded-mode"` should be `"--embedded-mode/--no-embedded-mode"` if we want to implement this.

**Comment by matentzn** [comment]
Yep, that would be great! Thanks!
