### ISSUE TITLE
Potential problem with read_pandas: # in rows

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#31]
Currently we ar using

```
pd.read_csv(filename, comment='#', sep=sep).fillna("")
```

To read a pandas data frame. This can be risky, due to the potential of hash symbols in the middle of rows. It would be more robust to manually skip rows which start with # and read the rest.

**Comment by matentzn** [comment]
@hrshdhgd can you check this is actually aproblem? if so just try and implement the above?

**Comment by hrshdhgd** [comment]
You are correct! When a '#' occurs in the data, pandas just turns everything after that as a 'NaN'

e.g.
I took part of your [test file](https://github.com/mapping-commons/sssom-py/blob/master/tests/validate_data/basic.tsv) as an input and added 2 '#'s in the first and third row.
```
#comment: .
#creator_id: cjm
#curie_map:
#  a: http://example.org/a/
#  rdfs: http://www.w3.org/2000/01/rdf-schema#
#  x: http://example.org/x/
#  y: http://example.org/y/
#  z: http://example.org/z/
#license: https://creativecommons.org/publicdomain/zero/1.0/
#mapping_date: '2020-05-30'
#mapping_tool: https://github.com/cmungall/rdf_matcher
#object_match_field: rdfs:label
#object_source: y
#subject_match_field: rdfs:label
#subject_source: z
subject_id	subject_label	subject_category	predicate_id	object_id	object_label	object_category	match_type	subject_source	object_source	mapping_tool	confidence	subject_match_field	object_match_field	match_string	comment
x:appendage	appendage	#biolink:AnatomicalEntity	owl:equivalentClass	y:appendage	appendages	biolink:AnatomicalEntity	Lexical|Stemming	x	y	rdf_matcher	0.8407144059077161	rdfs:label	rdfs:label	appendag	.
x:appendage	appendage	biolink:AnatomicalEntity	owl:equivalentClass	z:appendage	APPENDAGE	biolink:AnatomicalEntity	Lexical|Stemming	x	z	rdf_matcher	0.8407144059077161	rdfs:label	rdfs:label	appendag	.
x:appendage	appendage	#biolink:AnatomicalEntity	owl:equivalentClass	z:appendage	APPENDAGE	biolink:AnatomicalEntity	Lexical	x	z	rdf_matcher	0.8818562360532485	rdfs:label	rdfs:label	appendage	.
x:bone_element	bone element	biolink:AnatomicalEntity	owl:equivalentClass	y:bone	bones	biolink:AnatomicalEntity	Lexical	x	y	rdf_matcher	0.7387961250362586	oio:hasDbXref	oio:hasDbXref	UBERON:0001474	.

```

Pandas read this file as follows:
![Screen Shot 2021-04-29 at 11 06 52 AM](https://user-images.githubusercontent.com/5247075/116582689-3d9dfb80-a8db-11eb-87bf-cf9507f5b181.png)

Introduced 'NaN' in the rows following the '#'. 

I will look into addressing this.

**Comment by hrshdhgd** [comment]
One solution could be `df.dropna()` which results is this:
![Screen Shot 2021-04-29 at 11 18 47 AM](https://user-images.githubusercontent.com/5247075/116584281-cc5f4800-a8dc-11eb-86d4-0ca2981550f6.png)

But the side effect would be all rows which have at least 1 NaN in them would be dropped. I'm assuming that is not desirable?

**Comment by hrshdhgd** [comment]
A quick workaround:
![Screen Shot 2021-04-29 at 11 29 22 AM](https://user-images.githubusercontent.com/5247075/116585689-42b07a00-a8de-11eb-8215-c36a391fb475.png)


Thoughts?

**Comment by matentzn** [comment]
I am happy with that. What would be great: could you unify use of pd.read across the whole project:

![image](https://user-images.githubusercontent.com/7070631/116597325-67781200-a91d-11eb-922b-1a1a7ce766bc.png)


So we are just using the same method everywhere?

**Comment by hrshdhgd** [comment]
Done!

**Comment by matentzn** [comment]
Thanks@
