### ISSUE TITLE
Update pyparsing

### ISSUE THREAD

**Issue by cthoyt** [mapping-commons/sssom-py#313]
The fact that pyparsing is pinned to `2.4.7` is problematic since most people have updated. I have other packages I want to use at the same time as sssom-py that require newer versions.

If this is an upstream issue, e.g., with linkml, please help push this there.

**Comment by matentzn** [comment]
@hrshdhgd can we try to unpin pyparsing?

**Comment by cmungall** [comment]
It should never have been pinned in the first place, we should be avoiding
this practice in all our repos especially for libraries that are to be
widely used
