### ISSUE TITLE
Abstract the SSSOM File away from MappingSetDocument

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#32]
1. Create a new class `SSSOMDocument`
2. This class contains a MappingSetDocument and a direct reference to the pandas data frame
3. Replace all usages of MappingSetDocument in method signatures with SSSOMDocument

**Comment by cmungall** [comment]
This is what I started on here: https://github.com/mapping-commons/sssom-py/pull/36/files#diff-fb538a11597dd148685cbbbc64eb347c5a8dedd6e11e0a181eb7f256e6da9537R12-R21

**Comment by matentzn** [comment]
Yeap @hrshdhgd is working with your branch.
