### ISSUE TITLE
Clean up cli.py

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#33]
Check this for some chaotic brain dump: https://github.com/mapping-commons/sssom-py/blob/master/cli.md

- [x] All methods apart from `sssom parse`  should take as an input embedded SSSOM which is read properly using the internal model (fromTsv). No filetype inference needed at all, input MUST conform to embedded sssom (embedded means: metadata is on top of data frame)
- [x] Clean all CLI arguments to be uniform according to what is in cli.md above, or whatever you think is best and most understandable.
- [x] Add click metadata for help text (description of methods etc)

**Comment by hrshdhgd** [comment]
@matentzn , can we discuss these further during our next meeting?

**Comment by matentzn** [comment]
- [ ] Make sure that there are no more uses of the old MappingSetDocument logic in cli.py. Search for `.mapping_set` to find some problems.
