### ISSUE TITLE
Unpin `sqlalchemy` version

### ISSUE THREAD

**Issue by hrshdhgd** [mapping-commons/sssom-py#343]
SQLAlchemy version 2.0.x is not compatible with implementations upto version 1.4.46 as seen in #341 (bullet 2)

Dependent on https://github.com/yhat/pandasql/issues/102#issuecomment-1413970825

**Comment by cmungall** [comment]
sssom is a core library, we want to have as few constraints on its use as possible. unpinning from a specific version to `<2` is better but this still means that no one can use sssom in combination with the latest sqla which is not good.

Do we really need pandasql? Why not make this an optional add-in?
