### ISSUE TITLE
Prefixes missing in default prefix list

### ISSUE THREAD

**Issue by hrshdhgd** [mapping-commons/sssom-py#357]
Based on: 
- https://github.com/monarch-initiative/mondo/issues/6092
- https://github.com/monarch-initiative/mondo/pull/6093#pullrequestreview-1351164985

```
  Orphanet__2: https://www.orpha.net/ORDO/Orphanet_
  Orphanet__3: http://purl.obolibrary.org/obo/Orphanet_
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  owl: http://www.w3.org/2002/07/owl#
  semapv: https://w3id.org/semapv/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  sssom: https://w3id.org/sssom/
  oio: http://www.geneontology.org/formats/oboInOwl#
  
```

**Comment by hrshdhgd** [comment]
Is the `mondo.sssom.config.yml` manually curated in the mondo repo?

**Comment by matentzn** [comment]
Yes, it's manually curated! But the curie_map of a sssom file should never _need_ to have the built in properties provided.. They should be optional!

**Comment by cthoyt** [comment]
I think this was addressed with #431

**Comment by matentzn** [comment]
Yep.

**Comment by matentzn** [comment]
Thank you again :)
