### ISSUE TITLE
Add github actions workflow that refreshes sssom.context.external on a weekly bases

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#362]
Add github actions workflow that refreshes sssom.context.external on a weekly basis. This should also make a PR, which I can review.

You can model this action after this one:
https://github.com/INCATools/ontology-development-kit/blob/master/.github/workflows/constraints.yml

Right now, our prefixes are not up to date with bioregistry.

- [ ] ensure the semapv prefix is `https://w3id.org/semapv/vocab/`, note the trailing /vocab. Also search the code for any hard coded references to this namespace that may be wrong.

**Comment by anitacaron** [comment]
I can create this github action. How sssom.context.external is refreshed?

**Comment by matentzn** [comment]
Awesome @anitacaron the thanks for your comments:

Currently, I occasionally run this manually: https://github.com/mapping-commons/sssom-py/blob/master/Makefile#L51
