### ISSUE TITLE
Replace CURIE inference mechanism with curies.Converter.from_extended_prefix_map

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#363]
Right now, we are using the bioregistry bimap, and old bioregistry tooling for getting from CU:RIE string to URIs and back.

@cthoyt has now introduced the concept of "extended prefix maps" which are much more powerful for guessing and standardising prefixes then the bimap.

Here is a snippet:

```python
import curies

#: OBO context's extended prefix map
url = "https://github.com/biopragmatics/bioregistry/raw/main/exports/contexts/obo.epm.json"
converter = curies.Converter.from_extended_prefix_map(url)

>>> converter.expand("GO:1234567")
'http://purl.obolibrary.org/obo/GO_1234567'

>>> converter.compress("http://purl.obolibrary.org/obo/GO_1234567")
'GO:1234567'
>>> converter.compress("http://amigo.geneontology.org/amigo/term/GO:1234567")
'GO:1234567'

>>> converter.standardize_prefix("gomf")
'GO'
>>> converter.standardize_curie"gomf:1234567")
'GO:1234567'
>>> converter.standardize_uri("http://amigo.geneontology.org/amigo/term/GO:1234567")
'http://purl.obolibrary.org/obo/GO_1234567'
```

We should replace the old way of doing this with the new one.

For now, I still want to mirror the prefix map as part of the package rather than relying on bioregistry to doing the hosting/versioning.

**Comment by matentzn** [comment]
This is a mid-priority refactoring that can be done as a subsequent PR to #396

**Comment by matentzn** [comment]
As per discussion in #396, we can replace everything, including the built-in prefix map, with `curies`. 

Hwoever, I would like to ensure we have a test in place in the testing framework that ensures that whenever the epm is updated, the built-in prefixes are exactly what we expect them to be (which is **what is in sssom context**).

**Comment by cthoyt** [comment]
@matentzn this is effectively done besides #431
