### ISSUE TITLE
parse_sssom_table should take as an input a String, URI, or filepath

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#384]
Right now, parse_sssom_table can only do URI and filepath, but for various use cases like the SSSOM Validator UI, we need to be able to read the file from string.

I want to use this opportunity to clean up this method a bit, which is super convoluted as well.

**Comment by cthoyt** [comment]
This appears to be done already

https://github.com/mapping-commons/sssom-py/blob/41bcdca722f844a87d42c93c95e0ea6429747ea3/src/sssom/parsers.py#L78-L105

**Comment by matentzn** [comment]
Yep thats right!
