### ISSUE TITLE
New method: separate

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#39]
Break an SSSOM file into multiple SSSOM files such that any individual SSSOM file contains only mappings between two distinct ontologies. For example:

mapping.sssom.tsv:
```
A:001 skos:exactMatch B:001
A:002 skos:exactMatch B:005
A:001 skos:exactMatch C:001
```

should be broken into:

mapping_a_b.sssom.tsv:
```
A:001 skos:exactMatch B:001
A:002 skos:exactMatch B:005
```

mapping_a_c.sssom.tsv:
```
A:001 skos:exactMatch C:001
```

**Comment by cmungall** [comment]
There is a command already called partition. Happy to rename it partition
by clique or something

**Comment by matentzn** [comment]
Its somehow been implemented as "split" and works. Closing here.
