### ISSUE TITLE
When running sssom-py in -C merged mode, redundant prefixes are added

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#411]
```
tmp/%.sssom.tsv: tmp/mirror-%.json
	sssom parse tmp/mirror-$*.json --no-strict-clean-prefixes -I obographs-json -m $(METADATADIR)/mondo.sssom.config.yml -C merged -o $@
```

When running the above, both 

```
#   Orphanet: http://www.orpha.net/ORDO/Orphanet_
#   orphanet.ordo: http://www.orpha.net/ORDO/Orphanet_
```

are added to the `curie_map`. Only the one in the user-supplied metadata should be merged.

(This is what happens when I run the following in the Mondo ingest repo):

```
sh run.sh make mappings/mondo.sssom.tsv
```

Which has 

```
sssom                         0.3.40
sssom-schema                  0.15.0
```

**Comment by hrshdhgd** [comment]
Removing ` --no-strict-clean-prefixes` may fix the problem but is that what we want?

**Comment by matentzn** [comment]
I think the problem is that when we merge user-supplied prefix map we need to do one more step (pseudo-code):

Currently (something like):
```
user_supplied_prefix_map = {}
prefix_map = {}
prefix_map.addAll(add_all_bioregistry_prefix_map())
prefix_map.addAll(user_supplied_prefix_map) # this will overwrite the keys, so if user_supplied_prefix_map has a prefix in there that is also in the bioregistry, it will be overwritten
```

We need:

```
user_supplied_prefix_map = {}
prefix_map = {}
prefix_map.addAll(add_all_bioregistry_prefix_map())
for prefix, uri in user_supplied_prefix_map:
      # remove all key/value pairs in prefix_map where the value==uri
prefix_map.addAll(user_supplied_prefix_map) # add this only after the uri prefixes are removed.
```

Add least I think this is what is needed. 

The --no-strict-cleaning option should also be removed, but I assume (hope) removing it will only result in an error message!

**Comment by hrshdhgd** [comment]
When I run this locally , I do not get the `#   orphanet.ordo: http://www.orpha.net/ORDO/Orphanet_` prefix_map. Plus, there is no `mirror-*.json`, there is `mirror-*.owl`. I'm confused.

**Comment by hrshdhgd** [comment]
> I think the problem is that when we merge user-supplied prefix map we need to do one more step (pseudo-code):
> 
> Currently (something like):
> 
> ```
> user_supplied_prefix_map = {}
> prefix_map = {}
> prefix_map.addAll(add_all_bioregistry_prefix_map())
> prefix_map.addAll(user_supplied_prefix_map) # this will overwrite the keys, so if user_supplied_prefix_map has a prefix in there that is also in the bioregistry, it will be overwritten
> ```
> 
> We need:
> 
> ```
> user_supplied_prefix_map = {}
> prefix_map = {}
> prefix_map.addAll(add_all_bioregistry_prefix_map())
> for prefix, uri in user_supplied_prefix_map:
>       # remove all key/value pairs in prefix_map where the value==uri
> prefix_map.addAll(user_supplied_prefix_map) # add this only after the uri prefixes are removed.
> ```
> 
> Add least I think this is what is needed.
> 
> The --no-strict-cleaning option should also be removed, but I assume (hope) removing it will only result in an error message!

All of this is already in place. See this:
https://github.com/mapping-commons/sssom-py/blob/a23c4dd5a2c5496125a2f8a70e8723c86fce115f/src/sssom/context.py#L67-L89

**Comment by hrshdhgd** [comment]
But if `v` is present under a different `k` , you expect the `k` provided by the user should be be accepted in the case of a tie, correct?

**Comment by hrshdhgd** [comment]
In that case how about this:

```
if k not in prefix_map and v not in prefix_map.values():
    prefix_map[k] = v
```
