### ISSUE TITLE
Consider loosening Pandas dependency to include some 1.x versions

### ISSUE THREAD

**Issue by kevinschaper** [mapping-commons/sssom-py#432]
Recently sssom-py started requiring Pandas >= 2.0.3, which is colliding with other tooling we have which has a conservative upper limit on pandas of <2 (or ^1.x.x). In cat-merge, I found that 2.0.x was ok, but 2.1.x was not. I can look at kgx, but if sssom-py doesn't actually require a 2.x version of Pandas, it would be nice to walk back the requirement.

**Comment by matentzn** [comment]
Yes @hrshdhgd can you take care of that?

**Comment by hrshdhgd** [comment]
@cthoyt , you're actively working on the project. Is there a problem here?

**Comment by kevinschaper** [comment]
At this point I think we should just get cat-merge and kgx to both be compatible with a current version of pandas.
