### ISSUE TITLE
New command: sort

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#51]
See  https://github.com/mapping-commons/SSSOM/issues/39

We need a command that uses the canonical column order to sort an entire mapping set data frame correctly.

**Comment by cmungall** [comment]
I think this lower priority now we can just do `sssom dosql SELECT * FROM match ORDER BY ...`

**Comment by matentzn** [comment]
We need to be able to sort the columns by their canonical order, with a method like
https://github.com/mapping-commons/sssom-py/pull/158/files#diff-8e0eb781f6bf2cf74b9c6a904555d8bd7f214fef45ea8e55da8527f834e600e4L191

I am happy if the sort function could simply build on the the dosql command,  in combination with a canonical column ordering.

**Comment by hrshdhgd** [comment]
Does this sequence seem correct?

```
['subject_id', 'subject_label', 'subject_category', 'predicate_id', 'predicate_modifier', 'object_id', 'object_label', 'object_category', 'match_type', 'subject_source', 'object_source', 'mapping_tool', 'confidence', 'subject_match_field', 'object_match_field', 'match_string', 'comment']
```

This is the sequence in which slots are declared in [sssom.yaml](https://github.com/mapping-commons/sssom-py/blob/master/sssom/sssom.yaml)

**Comment by hrshdhgd** [comment]
It seems like `Mapping(**mdict)` already sorts the column names in the order it appears in `sssom.yaml` as slots thus keeping it a standard sequence. So a `sort` method is not needed(?). 

cc: @matentzn , @cmungall

**Comment by matentzn** [comment]
Sort needs to sort also the rows!

This here seems wrong:
https://github.com/monarch-initiative/mondo/blob/master/src/ontology/mappings/mondo_broadmatch_icd10cm.sssom.tsv

You can see it has a subject_label right at the end, while I would expect it to be after subject_id!

**Comment by hrshdhgd** [comment]
Aah .. I see why that's happening. Easy fix!

**Comment by hrshdhgd** [comment]
Now for rows, what would be the sort-by rule?

**Comment by hrshdhgd** [comment]
[Columns have been sorted!](https://github.com/monarch-initiative/mondo/blob/do-sql-makefile/src/ontology/mappings/mondo_broadmatch_icd10cm.sssom.tsv)
