### ISSUE TITLE
--input should accept file paths and urls

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#55]
It would be great if `--input` could generally except file paths and URLs. For example, from_tsv(tsv_path).

**Comment by hrshdhgd** [comment]
for reading purposes I'm going to change `filename` to `file_path` so it's clear in the code.

**Comment by matentzn** [comment]
Sound good!

**Comment by hrshdhgd** [comment]
Now will this be only a local path or could it also be a URL?

**Comment by matentzn** [comment]
Input should always allow both url or file; apart maybe parse, but just
pretend everywhere.

**Comment by hrshdhgd** [comment]
All above commits take care of this.

**Comment by matentzn** [comment]
Opening from URL does not work yet - can you maybe add a test to check why? I don't think we have any `open()` logic for URLs implemented? at least not that I can see.. e.g. read_csv and read_metadata

**Comment by matentzn** [comment]
In meeting with @hrshdhgd we tried extending the smart_open() method like:

```
@contextlib.contextmanager
def smart_open(filename=None):
    # https://stackoverflow.com/questions/17602878/how-to-handle-both-with-open-and-sys-stdout-nicely
    if filename and filename != "-":
        fh = open(filename, "w")
    elif validators.url(filename):
        fh = request.urlopen(filename)
    else:
        fh = sys.stdout
```

But that did not work.  Maybe consider https://2.python-requests.org/en/master/user/advanced/#id9

**Comment by matentzn** [comment]
also,smart_open should be able to 

```
def smart_open(filename=None, mode="r"):
    # https://stackoverflow.com/questions/17602878/how-to-handle-both-with-open-and-sys-stdout-nicely
    if filename and filename != "-":
        fh = open(filename, "w")
    elif validators.url(filename):
        fh = request.urlopen(filename)
    else:
        fh = sys.stdout
```

- [ ] smart open should also read and write - it reading, it should be able to open the file in read or write mode.

**Comment by matentzn** [comment]
This should work somehow:

cat test.sssom.tsv | sssom merge | sssom convert | sssom export > out.sssom.tsv

**Comment by cmungall** [comment]
clarified with @hrshdhgd that the pipes above are unix pipes - no need to chain within python!
