### ISSUE TITLE
MappingSetDataFrame should have a "merge" method

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#56]
MappingSetDataFrame should have a "merge" method with two parameters:

```
def merge(self, msdf, reconcile=True):
     // merging msdf into self, if reduce=True, then dedupe (remove redundant lower confidence mappings) and reconcile (if msdf contains a higher confidence _negative_ mapping, then remove lower confidence positive one. If confidence is the same, prefer HumanCurated. If both humancurated, prefer negative mapping). 
```

**Comment by matentzn** [comment]
I wrote this in a different context but maybe something along these lines:

```
    def _merge_mappings(self, mapping1: MappingSetDataFrame, mapping2: MappingSetDataFrame):
        """
        Should be in SSSOM TODO
        :return: merged MappingSetDataFrame
        """
        merged = MappingSetDataFrame()
        merged.df = mapping1.df.merge(mapping2.df)
        merged.prefixmap = mapping1.prefixmap
        for k in mapping2.prefixmap:
            if k not in merged.prefixmap:
                merged.prefixmap[k]=mapping2.prefixmap[k]
        merged.metadata = mapping1.metadata
        for k in mapping2.metadata:
            if k not in merged.metadata:
                merged.metadata[k]=mapping2.metadata[k]
        return merged
```

**Comment by matentzn** [comment]
During merge mapping1.merge(mapping2, reconcile) 

In reconcile mode:

1. Mappings in mapping1 trump mappings in mapping2 (so the new incoming mappings overwrite mappings in the first mappings set). 
2. Reconciling means two things
    1. if the same s,p,o (subject_id, object_id, predicate_id) is present multiple times, only preserve the highest confidence one. If confidence is same, rule 1 (above) applies.
    2. if `s,!p,o` and `s,p,o` and than prefer higher confidence and remove the other. If same confidence prefer "HumanCurated" . If same again prefer negative.
3. Prefixes:
     - if there is the same prefix in mapping1 as in mapping2, and the prefix URL is different, throw an error and fail hard
     - else just merge the two prefix maps
 3. Metadata: same as rule 1.

**Comment by matentzn** [comment]
maybe its best to 

1. first simply merge `msdf.merge(msdf2)`
2. call `msfd.reconcile()` to do the reconciliation

**Comment by hrshdhgd** [comment]
If `reconcile = False` ?

**Comment by hrshdhgd** [comment]
> Mappings in mapping1 trump mappings in mapping2 (so the new incoming mappings overwrite mappings in the first mappings set).

Also, I'm confused: The statement in parentheses seem to mean the opposite to the statement outside the parentheses. Please clarify.

**Comment by matentzn** [comment]
Ooops yes you are right, I fixed the phrasing, it was confused.

**Comment by matentzn** [comment]
> Can mapping1.metadata[k] and mapping2.metadata[k] have the same k but different values?

Yes it can, and in this case, we want an exception to be thrown and the program to stop.

**Comment by matentzn** [comment]
I don't know wether that's the name but I know @cmungall had implemented it somewhere!

**Comment by hrshdhgd** [comment]
I think it's [`dedupe`](https://github.com/mapping-commons/sssom-py/blob/f051e71841480d020d98736b97066637d84e33bb/sssom/cli.py#L90), @cmungall  ? But that takes in a file and spits out another. The main process occurs in  `filter_redundant_rows`, I think.

**Comment by matentzn** [comment]
Yes, it's whatever happens in dedupe

**Comment by hrshdhgd** [comment]
Also 
> if s,!p,o and s,p,o and than prefer higher confidence and remove the other. If same confidence prefer "HumanCurated" . If same again prefer negative. 

Where do I get the information of 'HumanCurated' ? Is this been done as well somewhere already or do I write new code?

**Comment by matentzn** [comment]
No it's supplied as part of the match_type column. We are likely to refine this further, so this should probably be a global variable somewhere. For no, just assume it's a string HumanCurated in a column "match_type"

**Comment by hrshdhgd** [comment]
Is there a test file for this such that it has all possible scenarios in a file? The test file `basic.tsv` has the same `predicate_id` for all rows. I could create a mock test file based on `basic.tsv` but I am not sure what all it would look like to encompass all possible scenarios we need to address.

**Comment by matentzn** [comment]
Can you try to create a new test file covering this use case? We also do not really have the `NOT` yet in the spec..

**Comment by matentzn** [comment]
This is done, thank you @hrshdhgd 

We will see how it fares in practice, probably I overlooked some cornercases during the design, but for now, this is fine!
