### ISSUE TITLE
reconcile write_sssom and write_tsv

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#61]
For some reason we have two methods to write sssom files:

write_sssom and write_tsv.

@hrshdhgd can you figure out how they are different?

**Comment by hrshdhgd** [comment]
So basically this is what `write_tsv` does:
1. `MappingSetDataFrame ` => 'MappingSetDocument`
2. Get DataFrame from msdf
3. `extract_global_meta` from `msdoc`
4. Delete filename
5. Reopen filename
6. Add `meta` from step 3 with a `#` at the beginning of each line
7. Append to this file with the DataFrame at the bottom

`write_sssom`
1. Grab `metadata` from msdf
2. Grab `prefixmap` and store it under `curie_map` 
3. Export `msdf.df` to tsv file with the 2 above.

Essentially they both do the same thing but `write_sssom` depends on `MappingSetDocument` object to get the metadata. I don't see anything about `prefixmap` in write_tsv which I assume is the old design (?) I think `write_sssom` can replace all occurrences of `write_tsv`

**Comment by matentzn** [comment]
Yes, I think so.. lets replace. Thanks for checking!

**Comment by matentzn** [comment]
Completed in #96
