### ISSUE TITLE
Apply `black` code style

### ISSUE THREAD

**Issue by cthoyt** [mapping-commons/sssom-py#64]
Even though it takes a bit of getting used to, the [`black`](https://github.com/psf/black) code formatter is proving to be a godsend on projects with multiple authors that all write python with slightly different styles.

I'm using it in all of my collaborative projects now, I'd suggest setting it up here. It's also possible to use a pre-commit hook so people can write code however they want, then it automatically fixes it just before pushing to github. Then you can also add a CI action to check that black has been applied before accepting PRs.

Let me know if you want me to add the config/docs that would help you get started. In the mean time, you could always see what happens when you do:

```bash
$ pip install black
$ black sssom/ tests/
```

**Comment by matentzn** [comment]
Absolutely, no shadow of a doubt!

@hrshdhgd when we are done with the #50 PR (i.e. when its merged in, and there are no more other open PRs), lets just do a single PR where we apply black to cli.py, io.py, parsers.py and writers.py.
