### ISSUE TITLE
Consider using click.option() instead of click.argument()

### ISSUE THREAD

**Issue by hrshdhgd** [mapping-commons/sssom-py#81]
After discussion with @matentzn , do we need consistency of CLI commands for using click.option() at certain commands and click.argument() for others?

As of now, click.argument() is used by:
- `diff`
- `partition`
- `dosql`
- `merge`

See [cli.py](https://github.com/mapping-commons/sssom-py/blob/issue_56/sssom/cli.py)

Cc: @cmungall

**Comment by matentzn** [comment]
I would like to use `click.option` throughout (like robot).

so for diff you can do 

```
sssom diff -i t1.sssom.tsv -i t2.sssom.tsv ...
sssom merge -i t1.sssom.tsv -i t2.sssom.tsv -i t2.sssom.tsv ...
```

because the commands that take a single sssom file in all use `--input/-i`..
