### ISSUE TITLE
What was the original idea to pass around contexts?

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#87]
All throughout SSSOM we see this context parameter to functions. I have always kinda thought of it as the prefixmap. Is there anything else a user should be able to pass? The context should be coming from SSSOM itself, while the prefixes can be passed in - or am I missing something?

**Comment by cmungall** [comment]
I think you can close

Jsonld context = prefix map

We passed it around prior to j SAS vying msdf object

**Comment by matentzn** [comment]
Thank you!
