### ISSUE TITLE
Downstream issue: `CCDH-Terminology-Service <-- linkml_runtime <-- sssom-py`; Incorrect import path

### ISSUE THREAD

**Issue by joeflack4** [mapping-commons/sssom-py#95]
## Related to
https://github.com/cancerDHC/ccdh-terminology-service/issues/28

## Background & error message
I'm working on the CCDH terminology service, which depends on linkml_runtime. When I try to start the service, it fails w/ the following error:

```
File "/src/sssom/sssom/sssom_datamodel.py", line 16, in <module>
from linkml.utils.slot import Slot
ModuleNotFoundError: No module named 'linkml.utils.slot'
```

## Possible solutions
It looks like the fix should be renaming the module path for all instances of `linkml.utils` like so:
`linkml.utils` --> `linkml_runtime.utils`

## Where I need help
I found that the source of the issue appears to be here, in `schema/sssom_datamodel.py`. However, Harold mentioned that this file is generated. I see at the top of the file that it says:

`# Auto generated from sssom.yaml by pythongen.py version: 0.9.0`

I've located [sssom.yaml](https://github.com/mapping-commons/sssom-py/blob/master/schema/sssom.yaml), but I don't see "`utils`" declared anywhere in that file. I'm not exactly sure how to modify this file to change it so that `linkml_runtime.utils` is what is generated instead of `linkml.utils`.

I can't find anywhere in the repo where `utils` is located in any yaml file. Is `sssom_datamodel.py` still being auto generated?
<img width="1171" alt="Screen Shot 2021-07-09 at 5 00 14 PM" src="https://user-images.githubusercontent.com/13045020/125135624-4da23a80-e0d7-11eb-98f1-d8ef9b48ad83.png">

**Comment by matentzn** [comment]
I have the same problem, but with a bit of luck this PR https://github.com/mapping-commons/sssom-py/pull/67 fixes this problem. I am a bit surprised you have sssom-py in your dependencies though. The interfaces are super unstable - in fact we will have our first "beta" release this summer, which will change almost all the interfaces on the CLI significantly. Can you track down where and how sssom-py is required by your infrastructure? Perhaps the right solution for you is to simply drop that dependency for now... cc @jiaola

**Comment by joeflack4** [comment]
@matentzn Yeah, I had no idea this was a dependency either. I'm pretty new at my organization. I was speaking with Harold Solbrig and he also recommends using LinkML 1.0.10.

**Comment by cmungall** [comment]
I think it makes sense for the terminology service in CCDH to use sssom-py -- but sorry I should have clarified some of the ongoing changes to other members of CCDH. If this becomes a problem for CCDH I can prioritize the work here for @hrshdhgd

**Comment by matentzn** [comment]
Of course it makes sense, but the upcoming release will break everything in the library.. it was not nearly ready for being integrated into any production systems! I think the best course of action for now is to remove the dependency - and add it back when the new version is out. Sorry for the inconvenience! I would still think we could benefit from understanding better how sssom py is used in CCDH..

**Comment by jiaola** [comment]
CCDH uses sssom-py to model the mapping and parse sssom input and generate sssom output. If there will be many changes, we can fix the dependency on a commit for now. We'll keep an eye on the changes and update the dependency once sssom-py is updated.

**Comment by matentzn** [comment]
The migration to the latest linkml is now complete, so issue should be resolved. Do you want to check on your end and let me know if not?
